# -*- coding: utf-8 -*-
"""alpha_pulse_final_output_creation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1madfnSUzbMPfr2jLSi20-z4yg077hRan
"""

import pandas as pd
import numpy as np

df = pd.read_csv("week5_finance_cleaned.csv")
df.head()

df.columns

df['name'].unique()

returns_wide = df.pivot(
    index='date',
    columns='name',
    values='daily_return'
)

returns_wide.head()

returns_wide = returns_wide.dropna()

num_stocks = returns_wide.shape[1]
weights = np.array([1/num_stocks] * num_stocks)
weights

returns_wide['Portfolio_Return'] = returns_wide.dot(weights)
returns_wide.head()

portfolio_df = returns_wide.reset_index()
portfolio_df.head()

portfolio_df.to_csv("alpha_pulse_portfolio.csv", index=False)

df.columns

df['daily_return'].isna().sum()

df = df.dropna(subset=['daily_return'])

returns_wide = df.pivot_table(
    index='date',
    columns='name',
    values='daily_return'
)

returns_wide.head()

returns_wide = returns_wide.dropna()

returns_wide.shape

num_stocks = returns_wide.shape[1]
weights = np.repeat(1/num_stocks, num_stocks)
weights

returns_wide['Portfolio_Return'] = returns_wide.dot(weights)

returns_wide.head()

portfolio_df = returns_wide.reset_index()
portfolio_df.head()

portfolio_df.to_csv("alpha_pulse_portfolio1.csv", index=False)

portfolio_df.columns

df = pd.read_csv("alpha_pulse_portfolio.csv")
df.head()

portfolio_returns = df['Portfolio_Return']

portfolio_returns.describe()

var_95 = np.percentile(portfolio_returns, 5)
var_99 = np.percentile(portfolio_returns, 1)
print("95% Historical VaR:", var_95)
print("99% Historical VaR:", var_99)

df['Rolling_Vol_30'] = portfolio_returns.rolling(30).std()

df[['date', 'Rolling_Vol_30']].dropna().head()

returns_only = df.drop(columns=['date', 'Portfolio_Return', 'Rolling_Vol_30'])

corr_matrix = returns_only.corr()
corr_matrix

corr_matrix.to_csv("correlation_matrix1.csv")

mean = portfolio_returns.mean()
std = portfolio_returns.std()

num_simulations = 10000
num_days = 252
simulated_returns = np.random.normal(mean, std, (num_simulations, num_days))
portfolio_paths = simulated_returns.cumsum(axis=1)

final_returns = portfolio_paths[:, -1]
mc_var_95 = np.percentile(final_returns, 5)
print("Monte Carlo VaR (95%):", mc_var_95)

stress_returns = portfolio_returns - 0.10
stress_var_95 = np.percentile(stress_returns, 5)
print("Stress VaR (95%):", stress_var_95)

df.to_csv("alpha_pulse_final_output.csv", index=False)

var_data = {
    "Metric": ["VaR_95", "VaR_99", "MC_VaR_95"],
    "Value": [var_95, var_99, mc_var_95]
}
var_df = pd.DataFrame(var_data)
var_df.to_csv("var_results.csv", index=False)
print("var_results.csv created")