# -*- coding: utf-8 -*-
"""Week 6: DataVisualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l1hxz1jWPuLvCh79vqwXkqFuFAHUwtq0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("week5_finance_cleaned.csv")
df.head()

df['date'] = pd.to_datetime(df['date'])

df.info()

df.describe()

plt.figure(figsize=(12,5))
plt.plot(df['date'], df['close'])
plt.title("Stock Price Trend Over Time")
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.show()

avg_price = df.groupby('name')['close'].mean()
plt.figure(figsize=(10,5))
avg_price.plot(kind='bar')
plt.title("Average Closing Price by Stock")
plt.xlabel("Stock Name")
plt.ylabel("Average Price")
plt.show()

plt.figure(figsize=(8,5))
plt.scatter(df['volume'], df['close'])
plt.title("Volume vs Closing Price")
plt.xlabel("Trading Volume")
plt.ylabel("Closing Price")
plt.show()

df['movement'] = df['daily_return'].apply(
    lambda x: 'Profit' if x > 0 else 'Loss'
)

df['movement'].value_counts()

movement_count = df['movement'].value_counts()

plt.figure(figsize=(6,6))
plt.pie(
    movement_count.values,
    labels=movement_count.index,
    autopct='%1.1f%%',
    startangle=90
)

plt.title("Profit vs Loss Days")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['daily_return'], kde=True)
plt.title("Distribution of Daily Returns")
plt.xlabel("Daily Return (%)")
plt.show()

plt.figure(figsize=(10,6))
corr = df[['open','high','low','close','volume']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

sns.pairplot(df[['open','high','low','close','volume']])
plt.show()

plt.plot(df['date'], df['close'])
plt.title("Trend: Closing Price Over Time")
plt.show()

sns.histplot(df['close'], kde=True)
plt.title("Distribution of Prices")
plt.show()

sns.heatmap(corr, annot=True)
plt.title("Relationship Between Financial Variables")
plt.show()