# -*- coding: utf-8 -*-
"""WEEK 5 : Exploratory Data Analysis (EDA) & Data Wrangling Using Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvrk9Wz-ulzfjGstOzPy4LM7vmQWwVSr
"""

import pandas as pd
import numpy as np

xls = pd.ExcelFile("finanace_Dashboard.xlsx")
xls.sheet_names

df = pd.read_excel(
    "finanace_Dashboard.xlsx",
    sheet_name="finance_Cleaned"
)

df.head()

df.shape

df.columns

df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

df.info()

df.isnull().sum()

num_cols = df.select_dtypes(include='number').columns
for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

df.duplicated().sum()

df = df.drop_duplicates()

df.columns

df['date'] = pd.to_datetime(df['date'])

df_2023 = df[df['year'] == 2023]

df.loc[0:5]

df.iloc[0:5, 0:4]

df['price_change'] = df['close'] - df['open']

df['trend'] = df['price_change'].apply(
    lambda x: 'Profit' if x > 0 else 'Loss'
)

df.groupby('name')['close'].mean()

df.groupby('name')['volume'].sum().sort_values(ascending=False)

pd.pivot_table(
    df,
    values='close',
    index='name',
    columns='trend',
    aggfunc='mean'
)

jan = df[df['month'] == 1]
feb = df[df['month'] == 2]
merged = pd.concat([jan, feb])
merged.head()

df.to_csv("week5_finance_cleaned.csv", index=False)